name: "Publish Jekyll"
description: "Sets up Ruby and builds the site with Jekyll"
runs:
  using: "composite"
  steps:
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3