# Sample workflow for building a Jekyll site 
name: Build Jekyll site 

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Jekyll
        uses: ./.github/actions/build
